### ISSUE TITLE
Problems using authorizer with React + NextJs

### ISSUE THREAD

**Issue by rodrigoimenes** [dirkbonhomme/pusher-js-auth#11]
Im facing issues when my "auth/pusher" endpoint is in another server (different from my client-side), for example:

client: localhost:3000
server: localhost:3001
authTransport is buffered.

pusher-auth.js:81 POST http://localhost:3000/api/auth/pusher 501 (Not Implemented)
If i change authEndpoint and put full URL (With localhost:3001) it works, connects as expected, but fails when retrivieving data giving error Invalid signature: Expected HMAC SHA256 hex digest of 124425.1545539

Obs¹: Actually i use this endpoint and it works fine, im only changing the frontend of this app.

Obs²: I've noticed that in this lib, [here](https://github.com/dirkbonhomme/pusher-js-auth/blob/da73d8f6ddbec62670e3ef1639a46776a6197fd2/lib/pusher-auth.js#L155), on authorize method, i could remove "host" for comparison,
cause i think im receiving this error for authEndpoint having the full URL, and blocking me joining the channel.

**Comment by dirkbonhomme** [comment]
Can you post the (anonymized) request and response from the call to your server?
