### ISSUE TITLE
npmjs

### ISSUE THREAD

**Issue by dincho** [dirkbonhomme/pusher-js-auth#3]
Any reason this is not published to npmjs?

**Comment by dirkbonhomme** [comment]
At the time I created this plugin, Pusher itself wasn't available on npmjs so there was no need to publish it over there.

I'll try to prepare a release that will be published to both npmjs and bower. Thanks for letting me know!

**Comment by dincho** [comment]
Great! Thank you

**Comment by dirkbonhomme** [comment]
Done! Version 1.2.0 is now available on npm and bower

**Comment by dincho** [comment]
Perfect! Thank you again
