### ISSUE TITLE
3.1 breaks pusher-js-auth

### ISSUE THREAD

**Issue by randallb** [dirkbonhomme/pusher-js-auth#4]
https://github.com/dirkbonhomme/pusher-js-auth/blob/df474d90643dd6791023fb701006e2e05fc8bd83/lib/pusher-auth.js#L95

That call breaks in version 3.1 of pusher-js, pushed 10 hours ago. We're rolling back to 3.0.0 figuring it won't be broken.

**Comment by dirkbonhomme** [comment]
Thanks! I'll investigate and try to fix it asap.

**Comment by dirkbonhomme** [comment]
@randallb This was not a small update 😆 I had to reverse engineer 3.1 and released it as 2.0.0 because it breaks compatibility with older versions. Please let me know if it works for you!
