### ISSUE TITLE
TypeError: 'undefined' is not an object (evaluating 'Pusher.Runtime')

### ISSUE THREAD

**Issue by abelski21** [dirkbonhomme/pusher-js-auth#5]
Hi,

I'm getting an error on our project's unit test after running npm install. It seems related to the last commit for pusher-auth.js a few days ago. I hope someone can help. Thanks. 

TypeError: 'undefined' is not an object (evaluating 'Pusher.Runtime')
  at /mnt/jenkins/workspace/master.widget/build/scripts/vendor/pubsub-js/node_modules/pusher-js-auth/lib/pusher-auth.js:150

**Comment by dirkbonhomme** [comment]
Hi @abelski21 

The latest version of this plugin is only compatible with the 3.1.0 version of Pusher. If you are running an older version I suggest to install 1.2.0 of this plugin: https://github.com/dirkbonhomme/pusher-js-auth/releases

I'm pretty sure this is what's breaking in your project. Please let me know if you've been able to resolve it.

**Comment by abelski21** [comment]
ah right. I already updated to the latest version. Forgot to change the path for the new pusher.js. I haven't seen the error now. Thanks!
