### ISSUE TITLE
Presence channel - not working

### ISSUE THREAD

**Issue by kailasvnair** [dirkbonhomme/pusher-js-auth#6]
not working with presence channel
VM40494:1 Uncaught SyntaxError: Unexpected token e in JSON at position 1
    at JSON.parse (<anonymous>)
    at pusher.min.js:9
    at pusher-auth.js:119
    at objectApply (pusher-auth.js:15)
    at pusher-auth.js:116
    at XMLHttpRequest.xhr.onreadystatechange (pusher-auth.js:58)

**Comment by kailasvnair** [comment]
'channel_data'  was not encoded as json . That caused the issue 


		foreach($channelList as $i => $channel) {
			//$status = ($channel === 'private-d')? 403 : 200;
			$status   = 200;
			$userInfo = json_encode(['user_id' => time()], true);
			
			$response[$channel] = [
				'status' => $status,
				'data'   => array (
								'auth' => $this->pusherKey . ':' . hash_hmac('sha256', $socketId . ':' . $channel . ':' . $userInfo,$this->pusherSecret,false),  
								'channel_data' => $userInfo
							)
			];
		}

**Comment by dirkbonhomme** [comment]
@kailasvnair Thanks! You've closed this ticket so I assume there's nothing we should fix in this library?

**Comment by scottweinert** [comment]
I also had this issue since I was not including the channel_data. The example in the README.md is a bit confusing since it does not include this key in the expected response from the server.

**Comment by dirkbonhomme** [comment]
Hi @scottweinert,

Can you provide a less confusing example for the README? Not exactly sure what you're referring to. Feel free to post an update here or create a PR.

Thanks!
