### ISSUE TITLE
Support for Pusher 4.1+ custom authorizer feature

### ISSUE THREAD

**Issue by stof** [dirkbonhomme/pusher-js-auth#7]
Pusher 4.1 introduced a new way to configure custom authorizers: https://github.com/pusher/pusher-js#authorizer-function

It would be great to refactor the plugin to benefit from it instead of extending Pusher internals. It would likely be less sensible to internal changes

**Comment by dirkbonhomme** [comment]
Cool! I should look into all the recent changes they've introduced.

Just to be clear, this plugin still works with 4.1 right?

**Comment by stof** [comment]
I haven't tried yet, but I think it does (they haven't done BC break on the existing auth layer internals when adding the new layer).

the migration should even be quite easy: remove the `Runtime` argument from your existing `buffered` function (it is not used by your implementation anyway), and expose it as a function that we can pass to the `authorizer` option.
after that, you can remove the `Pusher.Runtime.getAuthorizer` override (or keep and add a warning to deprecate it)

**Comment by dirkbonhomme** [comment]
Sorry for the late response. I haven't had time to look into this and it's not an urgent change for my own projects.

Feel free to pick it up yourself however and I'll gladly help you make the changes and get it merged.

Thanks!

**Comment by stof** [comment]
@dirkbonhomme I opened #9 to do it.
